export const FETCH_CITYNAME = 'fetch_cityname';
export const FETCH_CITYNAME_ERROR = 'fetch_cityname_error';
export const FETCH_AUTOCOMPLETE = 'fetch_autocomplete';
export const FETCH_AUTOCOMPLETE_ERROR = 'fetch_autocomplete_error';
export const FETCH_POSITION ="fetch_position";
export const FETCH_POSITION_ERROR = "fetch_position_error";
export const FETCH_RESTAURANT = 'fetch_restautrant';
export const FETCH_RESTAURANT_DETAILS = 'fetch_restautrant_details';
export const FETCH_RESTAURANT_ERROR = 'fetch_restautrant_error';
